# Generated by Django 5.0.6 on 2024-10-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post_user_profile_userprofile_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts', to='users.userprofile'),
        ),
    ]
